#!/usr/bin/env bash
# Configures a new Ubuntu machine
# First install nginx

apt-get update
apt-get install -y nginx

service nginx start
echo "Holberton school" > /var/www/html/index.nginx-debian.html
# Nginx HTTP: This profile opens only port 80
ufw allow 'Nginx HTTP'
service nginx restart