#!/usr/bin/env bash
# Configures a new Ubuntu machine
# First install nginx

apt-get update
apt-get -y install nginx

echo "Holberton school" > /var/www/html/index.nginx-debian.html
# Nginx HTTP: This profile opens only port 80
ufw allow 'Nginx HTTP'
service nginx restart