#!/usr/bin/env bash
# Install virtual machine nginx
sudo apt-get -y upgrade
sudo apt-get -y install nginx

sudo service nginx start
echo "Holberton School" > /var/www/html/index.nginx-debian.html
# Nginx HTTP: This profile opens only port 80
sudo ufw allow 'Nginx HTTP'
# Sed to add Rewrite, redirection configuration
sudo sed '/server_name _;/a rewrite ^/redirect_me http://soren-acevedo.tech/ permanent;' /etc/nginx/sites-available/default
sudo service nginx restart