#!/usr/bin/env bash
# Install virtual machine nginx
sudo apt-get -y upgrade
sudo apt-get -y install nginx

echo "Holberton School" > /var/www/html/index.nginx-debian.html

# Nginx HTTP: This profile opens only port 80
sudo ufw allow 'Nginx HTTP'

# Sed to personalizate error
echo "Ceci n'est pas une page" > /usr/share/nginx/html/error_page.html
sudo sed -i "/server_name _;/a error_page 404 /error_page.html; location = /error_page.html {root /usr/share/nginx/html; internal;}" /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart
