#!/usr/bin/env bash
# Install ufw
sudo apt-get update
sudo apt-get install ufw -y

#Set Up Defaults
sudo ufw default deny incoming
sudo ufw default allow outgoing

#Allow connections
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

#Turn It On
sudo ufw enable
